// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/authzv1/authz.proto

package iraaccessv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // ignored when as_admin = true
	AsAdmin       bool                   `protobuf:"varint,3,opt,name=as_admin,json=asAdmin,proto3" json:"as_admin,omitempty"`
	GrantedBy     string                 `protobuf:"bytes,4,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessRequest) Reset() {
	*x = GrantAccessRequest{}
	mi := &file_proto_authzv1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessRequest) ProtoMessage() {}

func (x *GrantAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzv1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_authzv1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *GrantAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GrantAccessRequest) GetAsAdmin() bool {
	if x != nil {
		return x.AsAdmin
	}
	return false
}

func (x *GrantAccessRequest) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

type GrantAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ZedToken      string                 `protobuf:"bytes,2,opt,name=zed_token,json=zedToken,proto3" json:"zed_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessResponse) Reset() {
	*x = GrantAccessResponse{}
	mi := &file_proto_authzv1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessResponse) ProtoMessage() {}

func (x *GrantAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzv1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_authzv1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *GrantAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GrantAccessResponse) GetZedToken() string {
	if x != nil {
		return x.ZedToken
	}
	return ""
}

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_proto_authzv1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzv1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_authzv1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_proto_authzv1_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzv1_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_authzv1_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type CheckAdminAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdminAccessRequest) Reset() {
	*x = CheckAdminAccessRequest{}
	mi := &file_proto_authzv1_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdminAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdminAccessRequest) ProtoMessage() {}

func (x *CheckAdminAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzv1_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdminAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAdminAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_authzv1_authz_proto_rawDescGZIP(), []int{4}
}

func (x *CheckAdminAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckAdminAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdminAccessResponse) Reset() {
	*x = CheckAdminAccessResponse{}
	mi := &file_proto_authzv1_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdminAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdminAccessResponse) ProtoMessage() {}

func (x *CheckAdminAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzv1_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdminAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAdminAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_authzv1_authz_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAdminAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_proto_authzv1_authz_proto protoreflect.FileDescriptor

const file_proto_authzv1_authz_proto_rawDesc = "" +
	"\n" +
	"\x19proto/authzv1/authz.proto\x12\tIraAccess\"\x84\x01\n" +
	"\x12GrantAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bas_admin\x18\x03 \x01(\bR\aasAdmin\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x04 \x01(\tR\tgrantedBy\"L\n" +
	"\x13GrantAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tzed_token\x18\x02 \x01(\tR\bzedToken\"J\n" +
	"\x12CheckAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"/\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"2\n" +
	"\x17CheckAdminAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x18CheckAdminAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2\x8b\x02\n" +
	"\x10IraAccessService\x12L\n" +
	"\vGrantAccess\x12\x1d.IraAccess.GrantAccessRequest\x1a\x1e.IraAccess.GrantAccessResponse\x12L\n" +
	"\vCheckAccess\x12\x1d.IraAccess.CheckAccessRequest\x1a\x1e.IraAccess.CheckAccessResponse\x12[\n" +
	"\x10CheckAdminAccess\x12\".IraAccess.CheckAdminAccessRequest\x1a#.IraAccess.CheckAdminAccessResponseB9Z7github.com/bhusha-n/authz/proto/iraaccessv1;iraaccessv1b\x06proto3"

var (
	file_proto_authzv1_authz_proto_rawDescOnce sync.Once
	file_proto_authzv1_authz_proto_rawDescData []byte
)

func file_proto_authzv1_authz_proto_rawDescGZIP() []byte {
	file_proto_authzv1_authz_proto_rawDescOnce.Do(func() {
		file_proto_authzv1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authzv1_authz_proto_rawDesc), len(file_proto_authzv1_authz_proto_rawDesc)))
	})
	return file_proto_authzv1_authz_proto_rawDescData
}

var file_proto_authzv1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_authzv1_authz_proto_goTypes = []any{
	(*GrantAccessRequest)(nil),       // 0: IraAccess.GrantAccessRequest
	(*GrantAccessResponse)(nil),      // 1: IraAccess.GrantAccessResponse
	(*CheckAccessRequest)(nil),       // 2: IraAccess.CheckAccessRequest
	(*CheckAccessResponse)(nil),      // 3: IraAccess.CheckAccessResponse
	(*CheckAdminAccessRequest)(nil),  // 4: IraAccess.CheckAdminAccessRequest
	(*CheckAdminAccessResponse)(nil), // 5: IraAccess.CheckAdminAccessResponse
}
var file_proto_authzv1_authz_proto_depIdxs = []int32{
	0, // 0: IraAccess.IraAccessService.GrantAccess:input_type -> IraAccess.GrantAccessRequest
	2, // 1: IraAccess.IraAccessService.CheckAccess:input_type -> IraAccess.CheckAccessRequest
	4, // 2: IraAccess.IraAccessService.CheckAdminAccess:input_type -> IraAccess.CheckAdminAccessRequest
	1, // 3: IraAccess.IraAccessService.GrantAccess:output_type -> IraAccess.GrantAccessResponse
	3, // 4: IraAccess.IraAccessService.CheckAccess:output_type -> IraAccess.CheckAccessResponse
	5, // 5: IraAccess.IraAccessService.CheckAdminAccess:output_type -> IraAccess.CheckAdminAccessResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_authzv1_authz_proto_init() }
func file_proto_authzv1_authz_proto_init() {
	if File_proto_authzv1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authzv1_authz_proto_rawDesc), len(file_proto_authzv1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authzv1_authz_proto_goTypes,
		DependencyIndexes: file_proto_authzv1_authz_proto_depIdxs,
		MessageInfos:      file_proto_authzv1_authz_proto_msgTypes,
	}.Build()
	File_proto_authzv1_authz_proto = out.File
	file_proto_authzv1_authz_proto_goTypes = nil
	file_proto_authzv1_authz_proto_depIdxs = nil
}
