syntax = "proto3";

package IraAccess;

option go_package = "github.com/bhusha-n/authz/proto/iraaccessv1;iraaccessv1";


service IraAccessService {

  rpc GrantAccess(GrantAccessRequest) returns (GrantAccessResponse);

  rpc CheckAccess(CheckAccessRequest) returns (CheckAccessResponse);

  rpc CheckAdminAccess(CheckAdminAccessRequest) returns (CheckAdminAccessResponse);

  rpc DeleteAccess(DeleteAccessRequest) returns (DeleteAccessResponse);

  rpc DeleteAdminAccess(DeleteAdminAccessRequest) returns (DeleteAdminAccessResponse);
}

message GrantAccessRequest {
  string user_id = 1;
  string tenant_id = 2; 
  bool as_admin = 3;
  string granted_by=4;
}

message GrantAccessResponse {
  bool success = 1;
  string zed_token = 2;
}

message DeleteAccessRequest{
  string user_id = 1;
  string tenant_id = 2;
  string deleted_by=4;
}

message DeleteAccessResponse{
  bool success = 1;
  string zed_token = 2;
}


message DeleteAdminAccessRequest{
  string user_id = 1;
  string deleted_by=4;
}

message DeleteAdminAccessResponse{
  bool success = 1;
  string zed_token = 2;
}

message CheckAccessRequest {
  string user_id = 1;
  string tenant_id = 2;
}

message CheckAccessResponse {
  bool allowed = 1;
}


message CheckAdminAccessRequest {
  string user_id = 1;
}

message CheckAdminAccessResponse {
  bool allowed = 1;
}


