// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/authzv1/authz.proto

package iraaccessv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IraAccessService_GrantAccess_FullMethodName      = "/IraAccess.IraAccessService/GrantAccess"
	IraAccessService_CheckAccess_FullMethodName      = "/IraAccess.IraAccessService/CheckAccess"
	IraAccessService_CheckAdminAccess_FullMethodName = "/IraAccess.IraAccessService/CheckAdminAccess"
)

// IraAccessServiceClient is the client API for IraAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IraAccessServiceClient interface {
	// GrantAccess makes a user a member of a tenant, or (when as_admin
	// is true) a platform admin with access to every tenant.
	GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*GrantAccessResponse, error)
	// CheckAccess checks whether a user can access a given tenant.
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
	CheckAdminAccess(ctx context.Context, in *CheckAdminAccessRequest, opts ...grpc.CallOption) (*CheckAdminAccessResponse, error)
}

type iraAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIraAccessServiceClient(cc grpc.ClientConnInterface) IraAccessServiceClient {
	return &iraAccessServiceClient{cc}
}

func (c *iraAccessServiceClient) GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*GrantAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantAccessResponse)
	err := c.cc.Invoke(ctx, IraAccessService_GrantAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iraAccessServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, IraAccessService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iraAccessServiceClient) CheckAdminAccess(ctx context.Context, in *CheckAdminAccessRequest, opts ...grpc.CallOption) (*CheckAdminAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAdminAccessResponse)
	err := c.cc.Invoke(ctx, IraAccessService_CheckAdminAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IraAccessServiceServer is the server API for IraAccessService service.
// All implementations must embed UnimplementedIraAccessServiceServer
// for forward compatibility.
type IraAccessServiceServer interface {
	// GrantAccess makes a user a member of a tenant, or (when as_admin
	// is true) a platform admin with access to every tenant.
	GrantAccess(context.Context, *GrantAccessRequest) (*GrantAccessResponse, error)
	// CheckAccess checks whether a user can access a given tenant.
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	CheckAdminAccess(context.Context, *CheckAdminAccessRequest) (*CheckAdminAccessResponse, error)
	mustEmbedUnimplementedIraAccessServiceServer()
}

// UnimplementedIraAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIraAccessServiceServer struct{}

func (UnimplementedIraAccessServiceServer) GrantAccess(context.Context, *GrantAccessRequest) (*GrantAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantAccess not implemented")
}
func (UnimplementedIraAccessServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedIraAccessServiceServer) CheckAdminAccess(context.Context, *CheckAdminAccessRequest) (*CheckAdminAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAdminAccess not implemented")
}
func (UnimplementedIraAccessServiceServer) mustEmbedUnimplementedIraAccessServiceServer() {}
func (UnimplementedIraAccessServiceServer) testEmbeddedByValue()                          {}

// UnsafeIraAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IraAccessServiceServer will
// result in compilation errors.
type UnsafeIraAccessServiceServer interface {
	mustEmbedUnimplementedIraAccessServiceServer()
}

func RegisterIraAccessServiceServer(s grpc.ServiceRegistrar, srv IraAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedIraAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IraAccessService_ServiceDesc, srv)
}

func _IraAccessService_GrantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IraAccessServiceServer).GrantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IraAccessService_GrantAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IraAccessServiceServer).GrantAccess(ctx, req.(*GrantAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IraAccessService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IraAccessServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IraAccessService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IraAccessServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IraAccessService_CheckAdminAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAdminAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IraAccessServiceServer).CheckAdminAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IraAccessService_CheckAdminAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IraAccessServiceServer).CheckAdminAccess(ctx, req.(*CheckAdminAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IraAccessService_ServiceDesc is the grpc.ServiceDesc for IraAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IraAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IraAccess.IraAccessService",
	HandlerType: (*IraAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrantAccess",
			Handler:    _IraAccessService_GrantAccess_Handler,
		},
		{
			MethodName: "CheckAccess",
			Handler:    _IraAccessService_CheckAccess_Handler,
		},
		{
			MethodName: "CheckAdminAccess",
			Handler:    _IraAccessService_CheckAdminAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authzv1/authz.proto",
}
